version: '3.2'
services:
  # MySQL
  local-db:
    image: mysql:8.0.23
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: DEVELOP_DATABASE
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      TZ: 'Asia/Tokyo'
    volumes:
      - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      # dockerコンテナとして起動したときに、ここにあるSQL文を実行
      - ./mysql/init:/docker-entrypoint-initdb.d
      # 永続化するときにマウントするdir
      - ./mysql/data:/var/lib/mysql
      # logの出力先
      - ./mysql/logs:/var/log/mysql
    ports:
      - 3306:3306
  # phpMyAdmin
  phpmyadmin:
    container_name: test_phpmyadmin
    image: phpmyadmin/phpmyadmin
    environment:
    - PMA_ARBITRARY=1
    - PMA_HOSTS=local-db
    - PMA_USER=docker
    - PMA_PASSWORD=docker
    ports:
    - 8080:80
  main:
    build:
      context: .
      dockerfile: ./ubuntu/Dockerfile
      args:
        USER_ID: 1000
        GROUP_ID: 1000
        USER_NAME: vscode
        GROUP_NAME: vscode
        WORK_DIR: develop
    env_file: devcontainer.env
    environment:
      - TZ=JST-9
    ports:
      - 3000:3000
    volumes:
      - ~/.ssh:/home/vscode/.ssh
    command: /bin/sh -c "while sleep 1000; do :; done"